version: '3.5'

services:
  app:
    container_name: aizonTest
    hostname: aizonTest
    command: 'npm start'
    environment:
      - "TZ=Europe/Barcelona"
    build: .
    ports:
      - "3000:80"
      - "9229:9229"
    env_file:
      - ./config/.env.development
    volumes:
      - .:/var/app
      - /var/app/node_modules

